### ISSUE TITLE
Transactions show with "Unknown Name"

### ISSUE THREAD

**Issue by andronachev** [square/connect-csharp-sdk#16]
Hello,

Transactions done using the Connect API (C# SDK) and with the Square embedded payment form (to get the credit card nonce), show up in the Dashboard with "Unknown Name". 

I see that it's not possible to send a First Name and a Last Name (not in C#, and also not with the embedded form). 

Is there a solution to this ? Maybe I haven't looked in the right place.

Thanks!

**Comment by tristansokol** [comment]
Are you looking to associate a transaction with a customer or with an item? For the former you'll need to submit a customer id with the transaction, and the latter isn't quite possible, but is something we are actively working on!

**Comment by jslaybaugh** [comment]
Just confirming on this because I'm seeing the same thing. I'm sending the `BillingAddress` (name, organization, address, locality, etc) and the `BuyerEmailAddress` but none of that is showing up in the Square Dashboard. Is there a way to see this information in Square at all? It makes it really hard for anyone to reconcile between our e-commerce system and the Square dashboard if there is really no way to connect them except apparently the `Note` field. (Even `ReferenceId` doesn't show up anywhere).

**Comment by tristansokol** [comment]
Could you explain a bit more about your use case? What are you trying to match up?

**Comment by jslaybaugh** [comment]
Well, here's an example of a transaction sent from my e-commerce integration. I'm sending my personal information in all the address, name, and email fields. I'm sending our system's order number in the reference ID field, but all that shows up anywhere is what I pass in the `Note` field. I guess the simple question is if we're sending all that data to Square, why isn't it available anywhere? Or perhaps it is and I'm just missing it. Is there anywhere to pull all the data that is sent?
<img width="1158" alt="screen shot 2017-04-12 at 8 51 28 am" src="https://cloud.githubusercontent.com/assets/306883/24964629/699dc410-1f67-11e7-8181-cd3f7892ad5b.png">

And the use case is really about problem resolution and trying to reconcile between two systems. We store the transaction Id from Square, so there is a single connection, but having a human-readable version always makes it simpler. I've connected our software with about 20 gateways over the past decade+ and every one of them has displayed this information (Authorize.net, PayPal, even Stripe) and I can also say that at one point or another every time there's been an issue or a question from a customer about a charge or something, its easier to look it up by name or order number instead of a random looking 20-character string.

**Comment by tristansokol** [comment]
Thanks for the feedback. Most of the information that you referenced is used in the case of a chargeback. We are actively working on increasing that data that gets propagated through other Square systems from our e-commerce API (like itemizations that you can read more about [here](https://medium.com/square-corner-blog/developer-night-recap-544bb900d0e1)). Do you attach your transactions to customers at all?

**Comment by iLoveSarabear** [comment]
Hello, was this ever resolved? I'm getting WooCommerce transactions in square with an "Unknown Name"

**Comment by itsmemanoj** [comment]
wow, the issue was raised in 2017 and still no words from the square.
Does not it makes sense, if we are sending information to API, then that information should be available on dashboard?
Inside the square dev team no one asked for this issue?
![2020-03-18](https://user-images.githubusercontent.com/48552515/76954459-7af23480-6938-11ea-8428-c78707abbd95.png)

**Comment by StephenJosey** [comment]
@itsmemanoj I'm not entirely sure what you're showing in that screenshot. It looks like an order that probably has more information once you click on it. What are you hoping to see? Instant profiles are accessible now, so I don't believe you should be seeing "Unknown Name" (which doesn't look like what you're reporting).

Also, if this is regarding WooCommerce in particular, they do support itemization now just to be clear, and you will see them in your Square Seller Dashboard.

**Comment by itsmemanoj** [comment]
@StephenJosey its not about WooCommerce.
And what I showed in that screenshot is Just Note field information that I posted to payment API.
No other information is there like Customer name, email, etc but I am posting those details.
I have to create a customer to see the name of the customer, But I don't want to create a customer there, I have already a system to manage my customers.
Am I able to clear the problem now?

**Comment by StephenJosey** [comment]
How are you posting those details if you're not creating a customer? The `CreatePayment` endpoint doesn't take a `customer_name` field, for instance. It takes a `customer_id` (meaning to create a customer via the Customers API). The other fields, such as `billing_address`, and `shipping_address`, do not get returned, if you're meaning those fields. They're meant to protect for chargeback protection. Unfortunately if you want to have customer details in Square, you will need to actually create a customer.
